services:
  marple-postgres:
    container_name: marple-postgres
    env_file:
    - .env
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
      - CMD-SHELL
      - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 5s
    image: docker.io/library/postgres:18-alpine
    ports:
    - ${POSTGRES_PORT:-5432}:5432
    volumes:
    - ${COMPOSE_PATH_ROOT}/postgres:/var/lib/postgresql
    restart: unless-stopped

  marple-garage:
    image: dxflrs/garage:v2.1.0
    container_name: marple-garage
    ports:
      - "3900:3900" # S3 API
      - "3903:3903" # Admin API
    volumes:
    - ./garage.toml:/etc/garage.toml
    - ${COMPOSE_PATH_ROOT}/garage/data:/var/lib/garage/data
    - ${COMPOSE_PATH_ROOT}/garage/meta:/var/lib/garage/meta
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test: ["CMD", "/garage", "status"]
      timeout: 5s
    restart: unless-stopped


  marple-insight:
    container_name: marple-insight
    image: docker.marpledata.com/library/marple-insight:${VERSION_INSIGHT:-1.21.1}
    env_file:
      - .env
    environment:
      MARPLE_DEPLOYMENT: $DEPLOYMENT
      MARPLE_POSTGRES_HOST: postgres
      MARPLE_POSTGRES_PORT: $POSTGRES_PORT
      MARPLE_POSTGRES_DB_NAME: $POSTGRES_DB
      MARPLE_POSTGRES_USER: $POSTGRES_USER
      MARPLE_POSTGRES_PW: $POSTGRES_PASSWORD
      MARPLE_IDP_PROVIDER: $IDP_PROVIDER
    ports:
      - ${COMPOSE_PORT_MARPLE:-80}:80 # first port is host
    volumes:
      - ${COMPOSE_PATH_ROOT}/insight:/srv/marple
    depends_on:
      - marple-postgres
    restart: unless-stopped

  marple-db:
    container_name: marple-db
    image: docker.marpledata.com/library/marpledb:${VERSION_DB:-2.11.1}
    env_file:
      - .env
    environment:
      MDB_DEPLOYMENT: $DEPLOYMENT
      MDB_DB_HOST: postgres
      MDB_DB_PORT: $POSTGRES_PORT
      MDB_DB_NAME: $POSTGRES_DB
      MDB_DB_USER: $POSTGRES_USER
      MDB_DB_PASSWORD: $POSTGRES_PASSWORD
      MDB_IDP_PROVIDER: $IDP_PROVIDER
      UVICORN_TIMEOUT_WORKER_HEALTHCHECK: 60 # Startup can take a while
    ports:
      - ${COMPOSE_PORT_DB:-8000}:80 # first port is host
    volumes:
      - ${COMPOSE_PATH_ROOT}/db:/srv/marpledb
    depends_on:
      - marple-postgres
      - marple-garage
    restart: unless-stopped

  
  marple-trino:
    container_name: marple-trino
    # Keep this pinned to the SPI version used by marpledb-trino-auth (see marpledb-trino-auth/pom.xml)
    image: trinodb/trino:479
    ports:
      - "9003:8080"
    environment:
      CATALOG_MANAGEMENT: dynamic
    volumes:
      # Password authenticator config
      - ./trino/config.properties:/etc/trino/config.properties:ro
    restart: unless-stopped