# For large file uploads
client_max_body_size 0; # Unlimited upload size, biggest file we've seen ~ 30GB
client_body_timeout 3600s;
proxy_read_timeout 3600s;


# Insight
server {
  server_name test.insight.marpledata.com; # TODO

  location / {
    proxy_pass  http://127.0.0.1:8000;
  }
}

# Database
server {
  server_name test.db.marpledata.com; # TODO

  location / {
    proxy_pass  http://127.0.0.1:8001;
  }
}

# Trino
server {
  server_name test.trino.marpledata.com; # TODO

  location / {
    proxy_pass  http://127.0.0.1:8080;
        proxy_set_header Host $host;

        # Tells Trino the original protocol was HTTPS
        proxy_set_header X-Forwarded-Proto $scheme;

        # Standard headers for logging and forwarding
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}


# IdP (remove if you have your own idp)
server {
  server_name test.dex.marpledata.com; # TODO

  location / {
    proxy_pass  http://127.0.0.1:8002;
  }
}